export const styles = {
  dialog: {
    width: "1294px",
    height: "698px",
    maxWidth: "none",
    maxHeight: "none",
    display: "flex",
    flexDirection: "column",
  },
  container: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontWeight: 600,
    mb: 2,
  },
  tabContainer: {
    mb: 3,
    borderBottom: "1px solid #E0E0E0",
  },
  searchContainer: {
    display: "flex",
    flexDirection: "column",
  },
  autocomplete: {
    width: "480px",
    height: "40px",
    "& .MuiInputBase-root": {
      height: "40px",
      padding: "14px 16px",
    },
    "& .MuiInputBase-input": {
      fontSize: "14px",
    },
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 2,
    mt: "auto",
    pt: 3,
  },
  table: {
    title: {
      padding: "11px 32px",
      backgroundColor: "#FFFFFF",
      border: "1px solid #EEEEEE",
      height: "40px",
      borderTopLeftRadius: "16px",
      borderTopRightRadius: "16px",
      display: "flex",
      alignItems: "center",
    },
    headerAndContent: {
      backgroundColor: "#FFFFFF",
      borderLeft: "1px solid #EEEEEE",
      borderRight: "1px solid #EEEEEE",
      height: "280px",
      overflow: "auto",
    },
    footer: {
      padding: "16px 32px",
      backgroundColor: "#FFFFFF",
      borderBottom: "1px solid #EEEEEE",
      borderLeft: "1px solid #EEEEEE",
      borderRight: "1px solid #EEEEEE",
      height: "26px",
      borderBottomLeftRadius: "16px",
      borderBottomRightRadius: "16px",
      borderTop: "1px solid #EEEEEE",
    },
    cell: {
      padding: "8px",
      fontFamily: "Noto Sans, sans-serif",
      fontSize: "12px",
      fontWeight: 500,
      lineHeight: "16.34px",
      textAlign: "left" as const,
      textUnderlinePosition: "from-font" as const,
      textDecorationSkipInk: "none" as const,
    },
    headerCell: {
      padding: "8px",
      fontFamily: "Noto Sans, sans-serif",
      fontSize: "12px",
      fontWeight: 600,
      lineHeight: "16.34px",
      textAlign: "left" as const,
      textUnderlinePosition: "from-font" as const,
      textDecorationSkipInk: "none" as const,
      borderBottom: "1px solid #EEEEEE",
    },
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "400px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #EEEEEE",
    borderRadius: "16px",
  },
  select: {
    minWidth: 120,
    fontSize: "12px",
    fontFamily: "Noto Sans, sans-serif",
    "& .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
  },
} as const;
