export const styles = {
  table: {
    title: {
      padding: "11px 32px",
      backgroundColor: "#FFFFFF",
      border: "1px solid #EEEEEE",
      height: "40px",
      borderTopLeftRadius: "16px",
      borderTopRightRadius: "16px",
      display: "flex",
      alignItems: "center",
    },
    headerAndContent: {
      backgroundColor: "#FFFFFF",
      borderLeft: "1px solid #EEEEEE",
      borderRight: "1px solid #EEEEEE",
      height: "280px",
      overflow: "auto",
    },
    footer: {
      padding: "16px 32px",
      backgroundColor: "#FFFFFF",
      borderBottom: "1px solid #EEEEEE",
      borderLeft: "1px solid #EEEEEE",
      borderRight: "1px solid #EEEEEE",
      height: "26px",
      borderBottomLeftRadius: "16px",
      borderBottomRightRadius: "16px",
      borderTop: "1px solid #EEEEEE",
    },
    cell: {
      padding: "8px",
      fontFamily: "Noto Sans, sans-serif",
      fontSize: "12px",
      fontWeight: 500,
      lineHeight: "16.34px",
      textAlign: "left" as const,
      textUnderlinePosition: "from-font" as const,
      textDecorationSkipInk: "none" as const,
    },
    headerCell: {
      padding: "8px",
      fontFamily: "Noto Sans, sans-serif",
      fontSize: "12px",
      fontWeight: 600,
      lineHeight: "16.34px",
      textAlign: "left" as const,
      textUnderlinePosition: "from-font" as const,
      textDecorationSkipInk: "none" as const,
      borderBottom: "1px solid #EEEEEE",
    },
  },
} as const;
