export const styles = {
  table: {
    title: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "11px 32px",
      borderBottom: "1px solid #EEEEEE",
      width: "1230px",
      height: "40px",
    },
    headerCell: {
      padding: "16px 20px 16px 32px",
      fontFamily: "Noto Sans, sans-serif",
      fontSize: "12px",
      fontWeight: 600,
      lineHeight: "16.34px",
      textAlign: "left" as const,
      borderBottom: "1px solid #EEEEEE",
    },
    cell: {
      padding: "8px 40px 8px 32px",
      fontFamily: "Noto Sans, sans-serif",
      fontSize: "12px",
      fontWeight: 600,
      lineHeight: "16.34px",
      textAlign: "left" as const,
      borderBottom: "1px solid #EEEEEE",
    },
    footer: {
      display: "flex",
      alignItems: "center",
      width: "1190px",
      height: "40px",
      padding: "16px 1142px 16px 32px",
    },
  },
  container: {
    padding: "32px",
  },
  statsContainer: {
    display: "flex",
    gap: 2,
    mb: 4,
  },
  statBox: {
    flex: 1,
    p: 2,
    border: "1px solid #e0e0e0",
    borderRadius: 1,
    display: "flex",
    alignItems: "center",
    gap: 2,
  },
  tableContainer: {
    border: "1px solid #e0e0e0",
    borderRadius: "16px",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    py: 8,
    textAlign: "center",
    height: "300px",
  },
  successAlert: {
    backgroundColor: "#CEF8E0",
    color: "#00653E",
    border: "1px solid #00653E",
    borderRadius: "16px",
    "& .MuiAlert-icon": { color: "#00653E" },
  },
};
